/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */  
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public class KeyPackageNameMetaData extends com.sybase.reflection.ClassMetaData
{
    /**
     * Sybase internal use only.
     */
    public KeyPackageNameMetaData()
    {
        super(com.afm.vhc.VHCDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(26);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData key_name_attribute = addAttributeWithParams
        	(612, "key_name", "string", 
        	255, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"key_name\"", "varchar(255)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData package_name_attribute = addAttributeWithParams
        	(614, "package_name", "string", 
        	100, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"package_name\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData user_name_attribute = addAttributeWithParams
        	(613, "user_name", "string", 
        	255, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"user_name\"", "varchar(255)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData domain_name_attribute = addAttributeWithParams
        	(615, "domain_name", "string", 
        	100, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"domain_name\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("KeyPackageName");
        
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return false;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}