/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */  
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public class LocalVHCResultStoreMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public LocalVHCResultStoreMetaData()
    {
        super(com.afm.vhc.VHCDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(16);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData ZZVHC_VALUE_attribute = addAttributeWithParams
        	(257, "ZZVHC_VALUE", "string?", 
        	300, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"d\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZZVHC_COMMENT_attribute = addAttributeWithParams
        	(258, "ZZVHC_COMMENT", "string?", 
        	100, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"e\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VBELN_attribute = addAttributeWithParams
        	(254, "VBELN", "string", 
        	10, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"a\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZZVHC_SECTIOID_attribute = addAttributeWithParams
        	(255, "ZZVHC_SECTIOID", "string", 
        	2, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"b\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZZVHC_QID_attribute = addAttributeWithParams
        	(256, "ZZVHC_QID", "string", 
        	4, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"c\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("LocalVHCResultStore");
        setSuperClassDefined(true);
        setTable("\"co_vhc_1_0_localvhcresultstore\"");
        setSynchronizationGroup("");
        com.sybase.reflection.IndexMetaData findByPrimaryKeyIndex_index = new com.sybase.reflection.IndexMetaData();
        findByPrimaryKeyIndex_index.setName("findByPrimaryKeyIndex");
        findByPrimaryKeyIndex_index.getAttributes().add(VBELN_attribute);
        findByPrimaryKeyIndex_index.getAttributes().add(ZZVHC_SECTIOID_attribute);
        findByPrimaryKeyIndex_index.getAttributes().add(ZZVHC_QID_attribute);
        this.getIndice().add(findByPrimaryKeyIndex_index);
        this.getKeyAttributes().add((VBELN_attribute));
        this.getKeyAttributes().add((ZZVHC_SECTIOID_attribute));
        this.getKeyAttributes().add((ZZVHC_QID_attribute));
        this.setKeyClass("LocalVHCResultStoreKey");
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}