/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */  
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public class LocalOrderStoreMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public LocalOrderStoreMetaData()
    {
        super(com.afm.vhc.VHCDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(15);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData DEBITOR_NAME_attribute = addAttributeWithParams
        	(229, "DEBITOR_NAME", "string?", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"b\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VHVIN_attribute = addAttributeWithParams
        	(230, "VHVIN", "string?", 
        	35, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"c\"", "varchar(35)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData LICPL_attribute = addAttributeWithParams
        	(231, "LICPL", "string?", 
        	15, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"d\"", "varchar(15)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CSTRYEAR_attribute = addAttributeWithParams
        	(232, "CSTRYEAR", "string?", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"e\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData SPART_TXT_attribute = addAttributeWithParams
        	(233, "SPART_TXT", "string?", 
        	20, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"f\"", "varchar(20)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VMODEL_TXT_attribute = addAttributeWithParams
        	(234, "VMODEL_TXT", "string?", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"g\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VISIT_START_DATE_attribute = addAttributeWithParams
        	(235, "VISIT_START_DATE", "date?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"h\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VISIT_START_TIME_attribute = addAttributeWithParams
        	(236, "VISIT_START_TIME", "time?", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"i\"", "time", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PNAME_attribute = addAttributeWithParams
        	(237, "PNAME", "string?", 
        	40, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"j\"", "varchar(40)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VBELN_attribute = addAttributeWithParams
        	(228, "VBELN", "string", 
        	10, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"a\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("LocalOrderStore");
        setSuperClassDefined(true);
        setTable("\"co_vhc_1_0_localorderstore\"");
        setSynchronizationGroup("");
        com.sybase.reflection.IndexMetaData findByPrimaryKeyIndex_index = new com.sybase.reflection.IndexMetaData();
        findByPrimaryKeyIndex_index.setName("findByPrimaryKeyIndex");
        findByPrimaryKeyIndex_index.getAttributes().add(VBELN_attribute);
        this.getIndice().add(findByPrimaryKeyIndex_index);
        this.getKeyAttributes().add((VBELN_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}