/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */  
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public class PersonalizationParametersMetaData extends com.sybase.reflection.ClassMetaData
{
    /**
     * Sybase internal use only.
     */
    public PersonalizationParametersMetaData()
    {
        super(com.afm.vhc.VHCDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(27);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData Plant_attribute = addAttributeWithParams
        	(624, "Plant", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Server,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData PlantUserDefined_attribute = addAttributeWithParams
        	(625, "PlantUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData Division_attribute = addAttributeWithParams
        	(626, "Division", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Server,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData DivisionUserDefined_attribute = addAttributeWithParams
        	(627, "DivisionUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData Salesorg_attribute = addAttributeWithParams
        	(628, "Salesorg", "string?", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Server,
        	false, false, true);
        com.sybase.reflection.AttributeMetaData SalesorgUserDefined_attribute = addAttributeWithParams
        	(629, "SalesorgUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CompanyCode_attribute = addAttributeWithParams
        	(630, "CompanyCode", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "2001", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Server,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData CompanyCodeUserDefined_attribute = addAttributeWithParams
        	(631, "CompanyCodeUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData OrderNo_attribute = addAttributeWithParams
        	(632, "OrderNo", "string?", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Server,
        	false, false, true);
        com.sybase.reflection.AttributeMetaData OrderNoUserDefined_attribute = addAttributeWithParams
        	(633, "OrderNoUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData UserId_attribute = addAttributeWithParams
        	(634, "UserId", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "EX_EVAG", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Server,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData UserIdUserDefined_attribute = addAttributeWithParams
        	(635, "UserIdUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData username_attribute = addAttributeWithParams
        	(636, "username", "string", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Session,
        	false, false, true);
        com.sybase.reflection.AttributeMetaData usernameUserDefined_attribute = addAttributeWithParams
        	(637, "usernameUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData password_attribute = addAttributeWithParams
        	(638, "password", "string", 
        	-1, 
        	false, false, true, false, false, 
        	true,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.Session,
        	true, false, true);
        com.sybase.reflection.AttributeMetaData passwordUserDefined_attribute = addAttributeWithParams
        	(639, "passwordUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("PersonalizationParameters");
        setSuperClassDefined(true);
        
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return false;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}