/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */  
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public class ServerPersonalizationMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public ServerPersonalizationMetaData()
    {
        super(com.afm.vhc.VHCDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(10);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData value_attribute = addAttributeWithParams
        	(617, "value", "string?", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"value\"", "LONG VARCHAR", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData user_defined_attribute = addAttributeWithParams
        	(618, "user_defined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"user_defined\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "true", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData package_script_version_attribute = addAttributeWithParams
        	(616, "package_script_version", "string", 
        	255, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"package_script_version\"", "varchar(255)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData key_name_attribute = addAttributeWithParams
        	(612, "key_name", "string", 
        	255, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"key_name\"", "varchar(255)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData user_name_attribute = addAttributeWithParams
        	(613, "user_name", "string", 
        	255, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"user_name\"", "varchar(255)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData package_name_attribute = addAttributeWithParams
        	(614, "package_name", "string", 
        	100, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"package_name\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData domain_name_attribute = addAttributeWithParams
        	(615, "domain_name", "string", 
        	100, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"domain_name\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("ServerPersonalization");
        setTable("\"personalization_key_values\"");
        setSynchronizationGroup("system");
        this.getKeyAttributes().add((key_name_attribute));
        this.getKeyAttributes().add((user_name_attribute));
        this.getKeyAttributes().add((package_name_attribute));
        this.getKeyAttributes().add((domain_name_attribute));
        this.setKeyClass("KeyPackageName");
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}