/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public  class SISSubscription extends com.sybase.sup.client.persistence.SISSubscription implements com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.SISSubscriptionMetaData META_DATA = new com.afm.vhc.intrnl.SISSubscriptionMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("SISSubscription", com.afm.vhc.intrnl.SISSubscription.class, "VHC.SISSubscription", META_DATA, com.afm.vhc.VHCDB.getDelegate());
}