/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public  class SISSubscriptionKey extends com.sybase.sup.client.persistence.SISSubscriptionKey implements com.sybase.reflection.ClassWithMetaData
{
    private static com.afm.vhc.intrnl.SISSubscriptionKeyMetaData META_DATA = new com.afm.vhc.intrnl.SISSubscriptionKeyMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("SISSubscriptionKey", com.afm.vhc.intrnl.SISSubscriptionKey.class, META_DATA, com.afm.vhc.VHCDB.getDelegate());
}