/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */  
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public class VHCLocalUploadQueueMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public VHCLocalUploadQueueMetaData()
    {
        super(com.afm.vhc.VHCDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(17);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData STATUS_attribute = addAttributeWithParams
        	(354, "STATUS", "int", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"c\"", "integer", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData VBELN_attribute = addAttributeWithParams
        	(352, "VBELN", "string", 
        	10, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"a\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData FILEPATH_attribute = addAttributeWithParams
        	(353, "FILEPATH", "string", 
        	200, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"b\"", "varchar(200)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("VHCLocalUploadQueue");
        setSuperClassDefined(true);
        setTable("\"co_vhc_1_0_vhclocaluploadqueue\"");
        setSynchronizationGroup("");
        com.sybase.reflection.IndexMetaData findByPrimaryKeyIndex_index = new com.sybase.reflection.IndexMetaData();
        findByPrimaryKeyIndex_index.setName("findByPrimaryKeyIndex");
        findByPrimaryKeyIndex_index.getAttributes().add(VBELN_attribute);
        findByPrimaryKeyIndex_index.getAttributes().add(FILEPATH_attribute);
        this.getIndice().add(findByPrimaryKeyIndex_index);
        this.getKeyAttributes().add((VBELN_attribute));
        this.getKeyAttributes().add((FILEPATH_attribute));
        this.setKeyClass("VHCLocalUploadQueueKey");
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}