/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */  
package com.afm.vhc.intrnl;

@SuppressWarnings("all")
public class Z_MF_SUBMIT_VHC_PIM_VHC_RESULTSMetaData extends com.sybase.reflection.ClassMetaData
{
    /**
     * Sybase internal use only.
     */
    public Z_MF_SUBMIT_VHC_PIM_VHC_RESULTSMetaData()
    {
        super(com.afm.vhc.VHCDB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(21);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData VBELN_attribute = addAttributeWithParams
        	(55, "VBELN", "string", 
        	10, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(10)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZZVHC_SECTIOID_attribute = addAttributeWithParams
        	(56, "ZZVHC_SECTIOID", "string", 
        	2, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(2)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZZVHC_QID_attribute = addAttributeWithParams
        	(57, "ZZVHC_QID", "string", 
        	4, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(4)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZZVHC_VALUE_attribute = addAttributeWithParams
        	(58, "ZZVHC_VALUE", "string", 
        	300, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData ZZVHC_COMMENT_attribute = addAttributeWithParams
        	(59, "ZZVHC_COMMENT", "string", 
        	100, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS");
        
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return false;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}