package com.afm.vhc;

/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
public abstract class EntityType
{
    public static int SearchOrder = 9;
    public static int VHCQuestionnaire = 12;
    public static int ET_BAPIRETURN = 1;
    public static int PEX_BAPIRETURN = 5;
    public static int PEX_VALUES = 6;
    public static int UserInfo = 11;
}