/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class LocalKeyGenerator extends com.sybase.sup.client.persistence.LocalKeyGenerator implements com.sybase.reflection.ClassWithMetaData
{
    static
    {
        kgMap.put("vhc:1.0", new com.afm.vhc.LocalKeyGenerator());
    }
    
    public LocalKeyGenerator()
    {
        super(com.afm.vhc.VHCDB.getDelegate(), "co_vhc_1_0_localkeygenerator", 100000);
    }
    
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.LocalKeyGeneratorMetaData META_DATA = new com.afm.vhc.intrnl.LocalKeyGeneratorMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("LocalKeyGenerator", com.afm.vhc.LocalKeyGenerator.class, "VHC.LocalKeyGenerator", META_DATA, com.afm.vhc.VHCDB.getDelegate());
        
    /**
     * Generate surrogate key.  
     */
    public static long generateId()
    {
        return com.afm.vhc.VHCDB.getDelegate().generateLocalId();
    }
    
    public static String generateGuid()
    {
    	return com.sybase.afx.util.StringUtil.guid32();
    }
}