/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class LocalVHCResultStoreKey extends com.sybase.persistence.AbstractStructure implements com.sybase.reflection.ClassWithMetaData
{
    private static com.afm.vhc.intrnl.LocalVHCResultStoreKeyMetaData META_DATA = new com.afm.vhc.intrnl.LocalVHCResultStoreKeyMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("LocalVHCResultStoreKey", com.afm.vhc.LocalVHCResultStoreKey.class, META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    /**
     * Creates an instance of com.afm.vhc.LocalVHCResultStoreKey  
     */
    public LocalVHCResultStoreKey()
    {
        this.setClassDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    
    private java.lang.String __VBELN ;  
    
    private java.lang.String __ZZVHC_SECTIOID ;  
    
    private java.lang.String __ZZVHC_QID ;  
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 378:
            return getVBELN();
        case 379:
            return getZZVHC_SECTIOID();
        case 380:
            return getZZVHC_QID();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 378:
            setVBELN((java.lang.String)v);
            break;
        case 379:
            setZZVHC_SECTIOID((java.lang.String)v);
            break;
        case 380:
            setZZVHC_QID((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    /**
     * get the value of VBELN  
     */
    public java.lang.String getVBELN()
    {
        
        return __VBELN;
    }
    
    /**
     * Set the value of VBELN  
     */
    public void setVBELN(java.lang.String value)
    {
        __VBELN = value;
    }
    
    /**
     * get the value of ZZVHC_SECTIOID  
     */
    public java.lang.String getZZVHC_SECTIOID()
    {
        
        return __ZZVHC_SECTIOID;
    }
    
    /**
     * Set the value of ZZVHC_SECTIOID  
     */
    public void setZZVHC_SECTIOID(java.lang.String value)
    {
        __ZZVHC_SECTIOID = value;
    }
    
    /**
     * get the value of ZZVHC_QID  
     */
    public java.lang.String getZZVHC_QID()
    {
        
        return __ZZVHC_QID;
    }
    
    /**
     * Set the value of ZZVHC_QID  
     */
    public void setZZVHC_QID(java.lang.String value)
    {
        __ZZVHC_QID = value;
    }
}