/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class LocalVHCResultStore extends com.sybase.persistence.AbstractLocalEntity implements com.sybase.persistence.LocalBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.LocalVHCResultStoreMetaData META_DATA = new com.afm.vhc.intrnl.LocalVHCResultStoreMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("LocalVHCResultStore", com.afm.vhc.LocalVHCResultStore.class, "VHC.LocalVHCResultStore", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __ZZVHC_VALUE ;  
    
    private java.lang.String __ZZVHC_COMMENT ;  
    
    private java.lang.String __VBELN ;  
    
    private java.lang.String __ZZVHC_SECTIOID ;  
    
    private java.lang.String __ZZVHC_QID ;  
    
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 257:
            return getZZVHC_VALUE();
        case 258:
            return getZZVHC_COMMENT();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 257:
            setZZVHC_VALUE((java.lang.String)v);
            break;
        case 258:
            setZZVHC_COMMENT((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 254:
            return getVBELN();
        case 255:
            return getZZVHC_SECTIOID();
        case 256:
            return getZZVHC_QID();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 254:
            setVBELN((java.lang.String)v);
            break;
        case 255:
            setZZVHC_SECTIOID((java.lang.String)v);
            break;
        case 256:
            setZZVHC_QID((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.LocalVHCResultStore  
     */
    public LocalVHCResultStore()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of ZZVHC_VALUE  
     */
    public java.lang.String getZZVHC_VALUE()
    {
        
        return __ZZVHC_VALUE;
    }
    
    /**
     * Set the value of ZZVHC_VALUE  
     */
    public void setZZVHC_VALUE(java.lang.String value)
    {
        if ((__ZZVHC_VALUE == null) != (value == null) || (value != null && ! value.equals(__ZZVHC_VALUE)))
        {
            _isDirty = true;
        }
        __ZZVHC_VALUE = value;
    }       
    /**
     * get the value of ZZVHC_COMMENT  
     */
    public java.lang.String getZZVHC_COMMENT()
    {
        
        return __ZZVHC_COMMENT;
    }
    
    /**
     * Set the value of ZZVHC_COMMENT  
     */
    public void setZZVHC_COMMENT(java.lang.String value)
    {
        if ((__ZZVHC_COMMENT == null) != (value == null) || (value != null && ! value.equals(__ZZVHC_COMMENT)))
        {
            _isDirty = true;
        }
        __ZZVHC_COMMENT = value;
    }       
    /**
     * get the value of VBELN  
     */
    public java.lang.String getVBELN()
    {
        
        return __VBELN;
    }
    
    /**
     * Set the value of VBELN  
     */
    public void setVBELN(java.lang.String value)
    {
        if ((__VBELN == null) != (value == null) || (value != null && ! value.equals(__VBELN)))
        {
            _isDirty = true;
        }
        __VBELN = value;
    }       
    /**
     * get the value of ZZVHC_SECTIOID  
     */
    public java.lang.String getZZVHC_SECTIOID()
    {
        
        return __ZZVHC_SECTIOID;
    }
    
    /**
     * Set the value of ZZVHC_SECTIOID  
     */
    public void setZZVHC_SECTIOID(java.lang.String value)
    {
        if ((__ZZVHC_SECTIOID == null) != (value == null) || (value != null && ! value.equals(__ZZVHC_SECTIOID)))
        {
            _isDirty = true;
        }
        __ZZVHC_SECTIOID = value;
    }       
    /**
     * get the value of ZZVHC_QID  
     */
    public java.lang.String getZZVHC_QID()
    {
        
        return __ZZVHC_QID;
    }
    
    /**
     * Set the value of ZZVHC_QID  
     */
    public void setZZVHC_QID(java.lang.String value)
    {
        if ((__ZZVHC_QID == null) != (value == null) || (value != null && ! value.equals(__ZZVHC_QID)))
        {
            _isDirty = true;
        }
        __ZZVHC_QID = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.LocalVHCResultStore find(com.afm.vhc.LocalVHCResultStoreKey id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalVHCResultStore.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id.getVBELN(),id.getZZVHC_SECTIOID(),id.getZZVHC_QID()};
            return (com.afm.vhc.LocalVHCResultStore)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.LocalVHCResultStore load(com.afm.vhc.LocalVHCResultStoreKey id)
    {
        return (com.afm.vhc.LocalVHCResultStore)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public com.afm.vhc.LocalVHCResultStoreKey _pk()
    {
        return (com.afm.vhc.LocalVHCResultStoreKey)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of LocalVHCResultStore
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore>)(Object)DELEGATE.findWithQuery(query, com.afm.vhc.LocalVHCResultStore.class);
    }
    
    /**
     * Find a List of Com.afm.vhc.LocalVHCResultStore
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalVHCResultStore.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"d\",x.\"e\",x.\"a\",x.\"b\",x.\"c\" FROM \"co_vhc_1_0_localvhcresultstore\" x";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                };
                Object[] values = new Object[] { 
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, com.afm.vhc.LocalVHCResultStore.class);
                return (com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.LocalVHCResultStore  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Com.afm.vhc.LocalVHCResultStore
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findByVBELN(java.lang.String VBELN, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalVHCResultStore.findByVBELN";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"d\",x.\"e\",x.\"a\",x.\"b\",x.\"c\" FROM \"co_vhc_1_0_localvhcresultstore\" x WHERE x.\"a\" = ?";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    VBELN,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, com.afm.vhc.LocalVHCResultStore.class);
                return (com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.LocalVHCResultStore  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findByVBELN(java.lang.String VBELN)
    {
        return findByVBELN(VBELN, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Com.afm.vhc.LocalVHCResultStore
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findByZZVHC_SECTIOID(java.lang.String ZZVHC_SECTIOID, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalVHCResultStore.findByZZVHC_SECTIOID";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"d\",x.\"e\",x.\"a\",x.\"b\",x.\"c\" FROM \"co_vhc_1_0_localvhcresultstore\" x WHERE x.\"b\" = ?";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    ZZVHC_SECTIOID,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, com.afm.vhc.LocalVHCResultStore.class);
                return (com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.LocalVHCResultStore  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findByZZVHC_SECTIOID(java.lang.String ZZVHC_SECTIOID)
    {
        return findByZZVHC_SECTIOID(ZZVHC_SECTIOID, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Com.afm.vhc.LocalVHCResultStore
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findByZZVHC_QID(java.lang.String ZZVHC_QID, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalVHCResultStore.findByZZVHC_QID";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"d\",x.\"e\",x.\"a\",x.\"b\",x.\"c\" FROM \"co_vhc_1_0_localvhcresultstore\" x WHERE x.\"c\" = ?";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    ZZVHC_QID,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, com.afm.vhc.LocalVHCResultStore.class);
                return (com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.LocalVHCResultStore  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> findByZZVHC_QID(java.lang.String ZZVHC_QID)
    {
        return findByZZVHC_QID(ZZVHC_QID, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a mobile business object Com.afm.vhc.LocalVHCResultStore
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.LocalVHCResultStore findByPrimaryKey(java.lang.String VBELN
                                                                   ,java.lang.String ZZVHC_SECTIOID
                                                                   ,java.lang.String ZZVHC_QID)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalVHCResultStore.findByPrimaryKey";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = "SELECT x.\"d\",x.\"e\",x.\"a\",x.\"b\",x.\"c\" FROM \"co_vhc_1_0_localvhcresultstore\" x WHERE x.\"a\" = ? AND x.\"b\" = ? AND x.\"c\" = ?";
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                    com.sybase.reflection.DataType.forName("string"),
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    VBELN,
                    ZZVHC_SECTIOID,
                    ZZVHC_QID,
                };
                Object res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, com.afm.vhc.LocalVHCResultStore.class);
                return (com.afm.vhc.LocalVHCResultStore)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LocalVHCResultStore>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
}