/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class LocalOrderStore extends com.sybase.persistence.AbstractLocalEntity implements com.sybase.persistence.LocalBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.LocalOrderStoreMetaData META_DATA = new com.afm.vhc.intrnl.LocalOrderStoreMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("LocalOrderStore", com.afm.vhc.LocalOrderStore.class, "VHC.LocalOrderStore", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __DEBITOR_NAME ;  
    
    private java.lang.String __VHVIN ;  
    
    private java.lang.String __LICPL ;  
    
    private java.lang.String __CSTRYEAR ;  
    
    private java.lang.String __SPART_TXT ;  
    
    private java.lang.String __VMODEL_TXT ;  
    
    private java.sql.Date __VISIT_START_DATE ;  
    
    private java.sql.Time __VISIT_START_TIME ;  
    
    private java.lang.String __PNAME ;  
    
    private java.lang.String __VBELN ;  
    
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 229:
            return getDEBITOR_NAME();
        case 230:
            return getVHVIN();
        case 231:
            return getLICPL();
        case 232:
            return getCSTRYEAR();
        case 233:
            return getSPART_TXT();
        case 234:
            return getVMODEL_TXT();
        case 237:
            return getPNAME();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 229:
            setDEBITOR_NAME((java.lang.String)v);
            break;
        case 230:
            setVHVIN((java.lang.String)v);
            break;
        case 231:
            setLICPL((java.lang.String)v);
            break;
        case 232:
            setCSTRYEAR((java.lang.String)v);
            break;
        case 233:
            setSPART_TXT((java.lang.String)v);
            break;
        case 234:
            setVMODEL_TXT((java.lang.String)v);
            break;
        case 237:
            setPNAME((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 228:
            return getVBELN();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 228:
            setVBELN((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public java.sql.Time getAttributeNullableTime(int id)
    {
        switch(id)
        {
        case 236:
            return getVISIT_START_TIME();
        default:
            return super.getAttributeNullableTime(id);
        }
    }
    
    public void setAttributeNullableTime(int id, java.sql.Time v)
    {
        switch(id)
        {
        case 236:
            setVISIT_START_TIME((java.sql.Time)v);
            break;
        default:
            super.setAttributeNullableTime(id, v);
            break;
        }
    }
    public java.sql.Date getAttributeNullableDate(int id)
    {
        switch(id)
        {
        case 235:
            return getVISIT_START_DATE();
        default:
            return super.getAttributeNullableDate(id);
        }
    }
    
    public void setAttributeNullableDate(int id, java.sql.Date v)
    {
        switch(id)
        {
        case 235:
            setVISIT_START_DATE((java.sql.Date)v);
            break;
        default:
            super.setAttributeNullableDate(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.LocalOrderStore  
     */
    public LocalOrderStore()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of DEBITOR_NAME  
     */
    public java.lang.String getDEBITOR_NAME()
    {
        
        return __DEBITOR_NAME;
    }
    
    /**
     * Set the value of DEBITOR_NAME  
     */
    public void setDEBITOR_NAME(java.lang.String value)
    {
        if ((__DEBITOR_NAME == null) != (value == null) || (value != null && ! value.equals(__DEBITOR_NAME)))
        {
            _isDirty = true;
        }
        __DEBITOR_NAME = value;
    }       
    /**
     * get the value of VHVIN  
     */
    public java.lang.String getVHVIN()
    {
        
        return __VHVIN;
    }
    
    /**
     * Set the value of VHVIN  
     */
    public void setVHVIN(java.lang.String value)
    {
        if ((__VHVIN == null) != (value == null) || (value != null && ! value.equals(__VHVIN)))
        {
            _isDirty = true;
        }
        __VHVIN = value;
    }       
    /**
     * get the value of LICPL  
     */
    public java.lang.String getLICPL()
    {
        
        return __LICPL;
    }
    
    /**
     * Set the value of LICPL  
     */
    public void setLICPL(java.lang.String value)
    {
        if ((__LICPL == null) != (value == null) || (value != null && ! value.equals(__LICPL)))
        {
            _isDirty = true;
        }
        __LICPL = value;
    }       
    /**
     * get the value of CSTRYEAR  
     */
    public java.lang.String getCSTRYEAR()
    {
        
        return __CSTRYEAR;
    }
    
    /**
     * Set the value of CSTRYEAR  
     */
    public void setCSTRYEAR(java.lang.String value)
    {
        if ((__CSTRYEAR == null) != (value == null) || (value != null && ! value.equals(__CSTRYEAR)))
        {
            _isDirty = true;
        }
        __CSTRYEAR = value;
    }       
    /**
     * get the value of SPART_TXT  
     */
    public java.lang.String getSPART_TXT()
    {
        
        return __SPART_TXT;
    }
    
    /**
     * Set the value of SPART_TXT  
     */
    public void setSPART_TXT(java.lang.String value)
    {
        if ((__SPART_TXT == null) != (value == null) || (value != null && ! value.equals(__SPART_TXT)))
        {
            _isDirty = true;
        }
        __SPART_TXT = value;
    }       
    /**
     * get the value of VMODEL_TXT  
     */
    public java.lang.String getVMODEL_TXT()
    {
        
        return __VMODEL_TXT;
    }
    
    /**
     * Set the value of VMODEL_TXT  
     */
    public void setVMODEL_TXT(java.lang.String value)
    {
        if ((__VMODEL_TXT == null) != (value == null) || (value != null && ! value.equals(__VMODEL_TXT)))
        {
            _isDirty = true;
        }
        __VMODEL_TXT = value;
    }       
    /**
     * get the value of VISIT_START_DATE  
     */
    public java.sql.Date getVISIT_START_DATE()
    {
        
        return __VISIT_START_DATE;
    }
    
    /**
     * Set the value of VISIT_START_DATE  
     */
    public void setVISIT_START_DATE(java.sql.Date value)
    {
        if ((__VISIT_START_DATE == null) != (value == null) || (value != null && ! value.equals(__VISIT_START_DATE)))
        {
            _isDirty = true;
        }
        __VISIT_START_DATE = value;
    }       
    /**
     * get the value of VISIT_START_TIME  
     */
    public java.sql.Time getVISIT_START_TIME()
    {
        
        return __VISIT_START_TIME;
    }
    
    /**
     * Set the value of VISIT_START_TIME  
     */
    public void setVISIT_START_TIME(java.sql.Time value)
    {
        if ((__VISIT_START_TIME == null) != (value == null) || (value != null && ! value.equals(__VISIT_START_TIME)))
        {
            _isDirty = true;
        }
        __VISIT_START_TIME = value;
    }       
    /**
     * get the value of PNAME  
     */
    public java.lang.String getPNAME()
    {
        
        return __PNAME;
    }
    
    /**
     * Set the value of PNAME  
     */
    public void setPNAME(java.lang.String value)
    {
        if ((__PNAME == null) != (value == null) || (value != null && ! value.equals(__PNAME)))
        {
            _isDirty = true;
        }
        __PNAME = value;
    }       
    /**
     * get the value of VBELN  
     */
    public java.lang.String getVBELN()
    {
        
        return __VBELN;
    }
    
    /**
     * Set the value of VBELN  
     */
    public void setVBELN(java.lang.String value)
    {
        if ((__VBELN == null) != (value == null) || (value != null && ! value.equals(__VBELN)))
        {
            _isDirty = true;
        }
        __VBELN = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.LocalOrderStore find(java.lang.String id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalOrderStore.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.LocalOrderStore)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.LocalOrderStore load(java.lang.String id)
    {
        return (com.afm.vhc.LocalOrderStore)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.String _pk()
    {
        return (java.lang.String)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of LocalOrderStore
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore>)(Object)DELEGATE.findWithQuery(query, com.afm.vhc.LocalOrderStore.class);
    }
    
    /**
     * Find a List of Com.afm.vhc.LocalOrderStore
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalOrderStore.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"a\" FROM \"co_vhc_1_0_localorderstore\" x";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                };
                Object[] values = new Object[] { 
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, com.afm.vhc.LocalOrderStore.class);
                return (com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.LocalOrderStore  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a mobile business object Com.afm.vhc.LocalOrderStore
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.LocalOrderStore findByPrimaryKey(java.lang.String VBELN)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LocalOrderStore.findByPrimaryKey";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = "SELECT x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"a\" FROM \"co_vhc_1_0_localorderstore\" x WHERE x.\"a\" = ?";
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    VBELN,
                };
                Object res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, com.afm.vhc.LocalOrderStore.class);
                return (com.afm.vhc.LocalOrderStore)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LocalOrderStore>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
}