/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class LogRecordImpl extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.LogRecord, com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.LogRecordImplMetaData META_DATA = new com.afm.vhc.intrnl.LogRecordImplMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("LogRecordImpl", com.afm.vhc.LogRecordImpl.class, "VHC.LogRecordImpl", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private int __level ;  
    
    private int __code ;  
    
    private java.lang.String __eisCode ;  
    
    private java.lang.String __message ;  
    
    private java.lang.String __component ;  
    
    private java.lang.String __entityKey ;  
    
    private java.lang.String __operation ;  
    
    private java.lang.String __requestId ;  
    
    private java.sql.Timestamp __timestamp ;  
    
      
    
      
    
      
    
      
    
    private long __messageId ;  
    
      
    
      
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 411:
            return getMessageId();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 411:
            setMessageId((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 414:
            return getEisCode();
        case 415:
            return getMessage();
        case 416:
            return getComponent();
        case 417:
            return getEntityKey();
        case 418:
            return getOperation();
        case 419:
            return getRequestId();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 414:
            setEisCode((java.lang.String)v);
            break;
        case 415:
            setMessage((java.lang.String)v);
            break;
        case 416:
            setComponent((java.lang.String)v);
            break;
        case 417:
            setEntityKey((java.lang.String)v);
            break;
        case 418:
            setOperation((java.lang.String)v);
            break;
        case 419:
            setRequestId((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    public java.sql.Timestamp getAttributeNullableDateTime(int id)
    {
        switch(id)
        {
        case 420:
            return getTimestamp();
        default:
            return super.getAttributeNullableDateTime(id);
        }
    }
    
    public void setAttributeNullableDateTime(int id, java.sql.Timestamp v)
    {
        switch(id)
        {
        case 420:
            setTimestamp((java.sql.Timestamp)v);
            break;
        default:
            super.setAttributeNullableDateTime(id, v);
            break;
        }
    }
    public int getAttributeInt(int id)
    {
        switch(id)
        {
        case 412:
            return getLevel();
        case 413:
            return getCode();
        default:
            return super.getAttributeInt(id);
        }
    }
    
    public void setAttributeInt(int id, int v)
    {
        switch(id)
        {
        case 412:
            setLevel((int)v);
            break;
        case 413:
            setCode((int)v);
            break;
        default:
            super.setAttributeInt(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.LogRecordImpl  
     */
    public LogRecordImpl()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of level  
     */
    public int getLevel()
    {
        
        return __level;
    }
    
    /**
     * Set the value of level  
     */
    public void setLevel(int value)
    {
        if(__level != value)
        {
            _isDirty = true;
        }
        __level = value;
    }       
    /**
     * get the value of code  
     */
    public int getCode()
    {
        
        return __code;
    }
    
    /**
     * Set the value of code  
     */
    public void setCode(int value)
    {
        if(__code != value)
        {
            _isDirty = true;
        }
        __code = value;
    }       
    /**
     * get the value of eisCode  
     */
    public java.lang.String getEisCode()
    {
        
        return __eisCode;
    }
    
    /**
     * Set the value of eisCode  
     */
    public void setEisCode(java.lang.String value)
    {
        if ((__eisCode == null) != (value == null) || (value != null && ! value.equals(__eisCode)))
        {
            _isDirty = true;
        }
        __eisCode = value;
    }       
    /**
     * get the value of message  
     */
    public java.lang.String getMessage()
    {
        
        return __message;
    }
    
    /**
     * Set the value of message  
     */
    public void setMessage(java.lang.String value)
    {
        if ((__message == null) != (value == null) || (value != null && ! value.equals(__message)))
        {
            _isDirty = true;
        }
        __message = value;
    }       
    /**
     * get the value of component  
     */
    public java.lang.String getComponent()
    {
        
        return __component;
    }
    
    /**
     * Set the value of component  
     */
    public void setComponent(java.lang.String value)
    {
        if ((__component == null) != (value == null) || (value != null && ! value.equals(__component)))
        {
            _isDirty = true;
        }
        __component = value;
    }       
    /**
     * get the value of entityKey  
     */
    public java.lang.String getEntityKey()
    {
        
        return __entityKey;
    }
    
    /**
     * Set the value of entityKey  
     */
    public void setEntityKey(java.lang.String value)
    {
        if ((__entityKey == null) != (value == null) || (value != null && ! value.equals(__entityKey)))
        {
            _isDirty = true;
        }
        __entityKey = value;
    }       
    /**
     * get the value of operation  
     */
    public java.lang.String getOperation()
    {
        
        return __operation;
    }
    
    /**
     * Set the value of operation  
     */
    public void setOperation(java.lang.String value)
    {
        if ((__operation == null) != (value == null) || (value != null && ! value.equals(__operation)))
        {
            _isDirty = true;
        }
        __operation = value;
    }       
    /**
     * get the value of requestId  
     */
    public java.lang.String getRequestId()
    {
        
        return __requestId;
    }
    
    /**
     * Set the value of requestId  
     */
    public void setRequestId(java.lang.String value)
    {
        if ((__requestId == null) != (value == null) || (value != null && ! value.equals(__requestId)))
        {
            _isDirty = true;
        }
        __requestId = value;
    }       
    /**
     * get the value of timestamp  
     */
    public java.sql.Timestamp getTimestamp()
    {
        
        return __timestamp;
    }
    
    /**
     * Set the value of timestamp  
     */
    public void setTimestamp(java.sql.Timestamp value)
    {
        if ((__timestamp == null) != (value == null) || (value != null && ! value.equals(__timestamp)))
        {
            _isDirty = true;
        }
        __timestamp = value;
    }       
    /**
     * get the value of messageId  
     */
    public long getMessageId()
    {
        
        return __messageId;
    }
    
    /**
     * Set the value of messageId  
     */
    public void setMessageId(long value)
    {
        if(__messageId != value)
        {
            _isDirty = true;
        }
        __messageId = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.LogRecordImpl find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "LogRecordImpl.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.LogRecordImpl)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.LogRecordImpl load(long id)
    {
        return (com.afm.vhc.LogRecordImpl)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of LogRecordImpl
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LogRecordImpl> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LogRecordImpl>)(Object)DELEGATE.findWithQuery(query, com.afm.vhc.LogRecordImpl.class);
    }
    
    
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LogRecordImpl> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LogRecordImpl>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.LogRecordImpl> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.LogRecordImpl>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("LogRecordImpl", keyToString());
    }
    
    
    
    
    
    
    
    
    
    
    
    public static com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> findByEntity(String entityName, String keyValue)
    {
        com.sybase.persistence.Query _query = com.sybase.persistence.AbstractEntity.getLogRecordQuery(entityName, keyValue);
        com.sybase.collections.GenericList<com.afm.vhc.LogRecordImpl> _logList = com.afm.vhc.LogRecordImpl.findWithQuery(_query);
        return (com.sybase.collections.GenericList<com.sybase.persistence.LogRecord>)(Object)_logList;
    }
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (getPendingChange() == 'C')
        {
            return "create";
        }
        else if (getPendingChange() == 'D')
        {
            return "delete";
        }
        else if (getPendingChange() == 'U')
        {
            return "update";
        }
        return null;
    }
    
    public com.afm.vhc.LogRecordImpl getDownloadState()
    {
        return (com.afm.vhc.LogRecordImpl)i_getDownloadState();
    }
    
    public com.afm.vhc.LogRecordImpl getOriginalState()
    {
        return (com.afm.vhc.LogRecordImpl)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}