/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class OfflineAuthentication extends com.sybase.persistence.AbstractLocalEntity implements com.sybase.persistence.LocalBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.OfflineAuthenticationMetaData META_DATA = new com.afm.vhc.intrnl.OfflineAuthenticationMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("OfflineAuthentication", com.afm.vhc.OfflineAuthentication.class, "VHC.OfflineAuthentication", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private int __passwordHash ;  
    
    private java.lang.String __user ;  
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 559:
            return getUser();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 559:
            setUser((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public int getAttributeInt(int id)
    {
        switch(id)
        {
        case 560:
            return getPasswordHash();
        default:
            return super.getAttributeInt(id);
        }
    }
    
    public void setAttributeInt(int id, int v)
    {
        switch(id)
        {
        case 560:
            setPasswordHash((int)v);
            break;
        default:
            super.setAttributeInt(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.OfflineAuthentication  
     */
    public OfflineAuthentication()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of passwordHash  
     */
    public int getPasswordHash()
    {
        
        return __passwordHash;
    }
    
    /**
     * Set the value of passwordHash  
     */
    public void setPasswordHash(int value)
    {
        if(__passwordHash != value)
        {
            _isDirty = true;
        }
        __passwordHash = value;
    }       
    /**
     * get the value of user  
     */
    public java.lang.String getUser()
    {
        
        return __user;
    }
    
    /**
     * Set the value of user  
     */
    public void setUser(java.lang.String value)
    {
        if ((__user == null) != (value == null) || (value != null && ! value.equals(__user)))
        {
            _isDirty = true;
        }
        __user = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.OfflineAuthentication find(java.lang.String id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OfflineAuthentication.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.OfflineAuthentication)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.OfflineAuthentication load(java.lang.String id)
    {
        return (com.afm.vhc.OfflineAuthentication)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.String _pk()
    {
        return (java.lang.String)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.OfflineAuthentication> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.OfflineAuthentication>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.OfflineAuthentication> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.OfflineAuthentication>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
}