/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class PersonalizationParameters extends com.sybase.sup.client.persistence.AbstractPersonalizationParameters implements com.sybase.reflection.ClassWithMetaData
{
    private static com.afm.vhc.intrnl.PersonalizationParametersMetaData META_DATA = new com.afm.vhc.intrnl.PersonalizationParametersMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("PersonalizationParameters", com.afm.vhc.PersonalizationParameters.class, META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    /**
     * Creates an instance of com.afm.vhc.PersonalizationParameters  
     */
    public PersonalizationParameters()
    {
        this.setClassDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
        clientPersonalizationTableName = "co_vhc_1_0_clientpersonalization";
        load();
    }
    
    private java.lang.String __Plant  = com.sybase.afx.json.JsonValue.getString("");  
    
    private boolean __PlantUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __Division  = com.sybase.afx.json.JsonValue.getString("");  
    
    private boolean __DivisionUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __Salesorg ;  
    
    private boolean __SalesorgUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __CompanyCode  = com.sybase.afx.json.JsonValue.getString("2001");  
    
    private boolean __CompanyCodeUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __OrderNo ;  
    
    private boolean __OrderNoUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __UserId  = com.sybase.afx.json.JsonValue.getString("EX_EVAG");  
    
    private boolean __UserIdUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __username ;  
    
    private boolean __usernameUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    private java.lang.String __password ;  
    
    private boolean __passwordUserDefined  = com.sybase.afx.json.JsonValue.getBoolean("false");  
    
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 628:
            return getSalesorg();
        case 632:
            return getOrderNo();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 628:
            setSalesorg((java.lang.String)v);
            break;
        case 632:
            setOrderNo((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 624:
            return getPlant();
        case 626:
            return getDivision();
        case 630:
            return getCompanyCode();
        case 634:
            return getUserId();
        case 636:
            return getUsername();
        case 638:
            return getPassword();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 624:
            setPlant((java.lang.String)v);
            break;
        case 626:
            setDivision((java.lang.String)v);
            break;
        case 630:
            setCompanyCode((java.lang.String)v);
            break;
        case 634:
            setUserId((java.lang.String)v);
            break;
        case 636:
            setUsername((java.lang.String)v);
            break;
        case 638:
            setPassword((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 625:
            return getPlantUserDefined();
        case 627:
            return getDivisionUserDefined();
        case 629:
            return getSalesorgUserDefined();
        case 631:
            return getCompanyCodeUserDefined();
        case 633:
            return getOrderNoUserDefined();
        case 635:
            return getUserIdUserDefined();
        case 637:
            return getUsernameUserDefined();
        case 639:
            return getPasswordUserDefined();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 625:
            setPlantUserDefined((boolean)v);
            break;
        case 627:
            setDivisionUserDefined((boolean)v);
            break;
        case 629:
            setSalesorgUserDefined((boolean)v);
            break;
        case 631:
            setCompanyCodeUserDefined((boolean)v);
            break;
        case 633:
            setOrderNoUserDefined((boolean)v);
            break;
        case 635:
            setUserIdUserDefined((boolean)v);
            break;
        case 637:
            setUsernameUserDefined((boolean)v);
            break;
        case 639:
            setPasswordUserDefined((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    /**
     * get the value of Plant  
     */
    public java.lang.String getPlant()
    {
        
        return __Plant;
    }
    
    /**
     * Set the value of Plant  
     */
    public void setPlant(java.lang.String value)
    {
        __Plant = value;
        if ( __PlantUserDefined == false )
        {
            __PlantUserDefined = true;
        }
    }
    
    /**
     * get the value of PlantUserDefined  
     */
    public boolean getPlantUserDefined()
    {
        
        return __PlantUserDefined;
    }
    
    /**
     * Set the value of PlantUserDefined  
     */
    private void setPlantUserDefined(boolean value)
    {
        __PlantUserDefined = value;
    }
    
    /**
     * get the value of Division  
     */
    public java.lang.String getDivision()
    {
        
        return __Division;
    }
    
    /**
     * Set the value of Division  
     */
    public void setDivision(java.lang.String value)
    {
        __Division = value;
        if ( __DivisionUserDefined == false )
        {
            __DivisionUserDefined = true;
        }
    }
    
    /**
     * get the value of DivisionUserDefined  
     */
    public boolean getDivisionUserDefined()
    {
        
        return __DivisionUserDefined;
    }
    
    /**
     * Set the value of DivisionUserDefined  
     */
    private void setDivisionUserDefined(boolean value)
    {
        __DivisionUserDefined = value;
    }
    
    /**
     * get the value of Salesorg  
     */
    public java.lang.String getSalesorg()
    {
        
        return __Salesorg;
    }
    
    /**
     * Set the value of Salesorg  
     */
    public void setSalesorg(java.lang.String value)
    {
        __Salesorg = value;
        if ( __SalesorgUserDefined == false )
        {
            __SalesorgUserDefined = true;
        }
    }
    
    /**
     * get the value of SalesorgUserDefined  
     */
    public boolean getSalesorgUserDefined()
    {
        
        return __SalesorgUserDefined;
    }
    
    /**
     * Set the value of SalesorgUserDefined  
     */
    private void setSalesorgUserDefined(boolean value)
    {
        __SalesorgUserDefined = value;
    }
    
    /**
     * get the value of CompanyCode  
     */
    public java.lang.String getCompanyCode()
    {
        
        return __CompanyCode;
    }
    
    /**
     * Set the value of CompanyCode  
     */
    public void setCompanyCode(java.lang.String value)
    {
        __CompanyCode = value;
        if ( __CompanyCodeUserDefined == false )
        {
            __CompanyCodeUserDefined = true;
        }
    }
    
    /**
     * get the value of CompanyCodeUserDefined  
     */
    public boolean getCompanyCodeUserDefined()
    {
        
        return __CompanyCodeUserDefined;
    }
    
    /**
     * Set the value of CompanyCodeUserDefined  
     */
    private void setCompanyCodeUserDefined(boolean value)
    {
        __CompanyCodeUserDefined = value;
    }
    
    /**
     * get the value of OrderNo  
     */
    public java.lang.String getOrderNo()
    {
        
        return __OrderNo;
    }
    
    /**
     * Set the value of OrderNo  
     */
    public void setOrderNo(java.lang.String value)
    {
        __OrderNo = value;
        if ( __OrderNoUserDefined == false )
        {
            __OrderNoUserDefined = true;
        }
    }
    
    /**
     * get the value of OrderNoUserDefined  
     */
    public boolean getOrderNoUserDefined()
    {
        
        return __OrderNoUserDefined;
    }
    
    /**
     * Set the value of OrderNoUserDefined  
     */
    private void setOrderNoUserDefined(boolean value)
    {
        __OrderNoUserDefined = value;
    }
    
    /**
     * get the value of UserId  
     */
    public java.lang.String getUserId()
    {
        
        return __UserId;
    }
    
    /**
     * Set the value of UserId  
     */
    public void setUserId(java.lang.String value)
    {
        __UserId = value;
        if ( __UserIdUserDefined == false )
        {
            __UserIdUserDefined = true;
        }
    }
    
    /**
     * get the value of UserIdUserDefined  
     */
    public boolean getUserIdUserDefined()
    {
        
        return __UserIdUserDefined;
    }
    
    /**
     * Set the value of UserIdUserDefined  
     */
    private void setUserIdUserDefined(boolean value)
    {
        __UserIdUserDefined = value;
    }
    
    /**
     * get the value of username  
     */
    public java.lang.String getUsername()
    {
        
        return __username;
    }
    
    /**
     * Set the value of username  
     */
    public void setUsername(java.lang.String value)
    {
        __username = value;
        if ( __usernameUserDefined == false )
        {
            __usernameUserDefined = true;
        }
    }
    
    /**
     * get the value of usernameUserDefined  
     */
    public boolean getUsernameUserDefined()
    {
        
        return __usernameUserDefined;
    }
    
    /**
     * Set the value of usernameUserDefined  
     */
    private void setUsernameUserDefined(boolean value)
    {
        __usernameUserDefined = value;
    }
    
    /**
     * get the value of password  
     */
    public java.lang.String getPassword()
    {
        
        return __password;
    }
    
    /**
     * Set the value of password  
     */
    public void setPassword(java.lang.String value)
    {
        __password = value;
        if ( __passwordUserDefined == false )
        {
            __passwordUserDefined = true;
        }
    }
    
    /**
     * get the value of passwordUserDefined  
     */
    public boolean getPasswordUserDefined()
    {
        
        return __passwordUserDefined;
    }
    
    /**
     * Set the value of passwordUserDefined  
     */
    private void setPasswordUserDefined(boolean value)
    {
        __passwordUserDefined = value;
    }
    
    
    
    protected void reset()
    {
        super.reset();
    }
}