/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class PEX_VALUES extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.PEX_VALUESMetaData META_DATA = new com.afm.vhc.intrnl.PEX_VALUESMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("PEX_VALUES", com.afm.vhc.PEX_VALUES.class, "VHC.PEX_VALUES", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __SECTION_ID ;  
    
    private java.lang.String __QUES_ID ;  
    
    private java.math.BigDecimal __SEQUENCE ;  
    
    private java.lang.String __VALUE ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 311:
            return getSurrogateKey();
        case 1359:
            return getCvpOperationLength();
        case 1360:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 311:
            setSurrogateKey((long)v);
            break;
        case 1359:
            setCvpOperationLength((long)v);
            break;
        case 1360:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 845:
            return getCvpOperation();
        case 846:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.math.BigDecimal getAttributeDecimal(int id)
    {
        switch(id)
        {
        case 309:
            return getSEQUENCE();
        default:
            return super.getAttributeDecimal(id);
        }
    }
    
    public void setAttributeDecimal(int id, java.math.BigDecimal v)
    {
        switch(id)
        {
        case 309:
            setSEQUENCE((java.math.BigDecimal)v);
            break;
        default:
            super.setAttributeDecimal(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 307:
            return getSECTION_ID();
        case 308:
            return getQUES_ID();
        case 310:
            return getVALUE();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 307:
            setSECTION_ID((java.lang.String)v);
            break;
        case 308:
            setQUES_ID((java.lang.String)v);
            break;
        case 310:
            setVALUE((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.PEX_VALUES  
     */
    public PEX_VALUES()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of SECTION_ID  
     */
    public java.lang.String getSECTION_ID()
    {
        
        return __SECTION_ID;
    }
    
    /**
     * Set the value of SECTION_ID  
     */
    public void setSECTION_ID(java.lang.String value)
    {
        if ((__SECTION_ID == null) != (value == null) || (value != null && ! value.equals(__SECTION_ID)))
        {
            _isDirty = true;
        }
        __SECTION_ID = value;
    }       
    /**
     * get the value of QUES_ID  
     */
    public java.lang.String getQUES_ID()
    {
        
        return __QUES_ID;
    }
    
    /**
     * Set the value of QUES_ID  
     */
    public void setQUES_ID(java.lang.String value)
    {
        if ((__QUES_ID == null) != (value == null) || (value != null && ! value.equals(__QUES_ID)))
        {
            _isDirty = true;
        }
        __QUES_ID = value;
    }       
    /**
     * get the value of SEQUENCE  
     */
    public java.math.BigDecimal getSEQUENCE()
    {
        
        return __SEQUENCE;
    }
    
    /**
     * Set the value of SEQUENCE  
     */
    public void setSEQUENCE(java.math.BigDecimal value)
    {
        if ((__SEQUENCE == null) != (value == null) || (value != null && ! value.equals(__SEQUENCE)))
        {
            _isDirty = true;
        }
        __SEQUENCE = value;
    }       
    /**
     * get the value of VALUE  
     */
    public java.lang.String getVALUE()
    {
        
        return __VALUE;
    }
    
    /**
     * Set the value of VALUE  
     */
    public void setVALUE(java.lang.String value)
    {
        if ((__VALUE == null) != (value == null) || (value != null && ! value.equals(__VALUE)))
        {
            _isDirty = true;
        }
        __VALUE = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.PEX_VALUES find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "PEX_VALUES.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.PEX_VALUES)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.PEX_VALUES load(long id)
    {
        return (com.afm.vhc.PEX_VALUES)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of PEX_VALUES
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES>)(Object)DELEGATE.findWithQuery(query, com.afm.vhc.PEX_VALUES.class);
    }
    
    /**
     * Find a List of Com.afm.vhc.PEX_VALUES
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "PEX_VALUES.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"e\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"vhc_1_0_pex_values\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"e\" from \"vhc_1_0_pex_values_os\" x_os where x_os.\"e\" = "
                                                + "x.\"e\"))))"; 
            return (com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, com.afm.vhc.PEX_VALUES.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.PEX_VALUES  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Com.afm.vhc.PEX_VALUES
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES> findBySecIdQID(java.lang.String section_Id, java.lang.String Ques_Id, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "PEX_VALUES.findBySecIdQID";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"e\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"vhc_1_0_pex_values\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"e\" from \"vhc_1_0_pex_values_os\" x_os where x_os.\"e\" = "
                                        + "x.\"e\")))) and ( x.\"a\" = ? AND x.\"b\" = ?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    section_Id,
                    Ques_Id,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, com.afm.vhc.PEX_VALUES.class);
                return (com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.PEX_VALUES  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES> findBySecIdQID(java.lang.String section_Id,java.lang.String Ques_Id)
    {
        return findBySecIdQID(section_Id, Ques_Id, 0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.PEX_VALUES>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("PEX_VALUES", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public com.afm.vhc.PEX_VALUES getDownloadState()
    {
        return (com.afm.vhc.PEX_VALUES)i_getDownloadState();
    }
    
    public com.afm.vhc.PEX_VALUES getOriginalState()
    {
        return (com.afm.vhc.PEX_VALUES)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}