/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class SearchOrder extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.SearchOrderMetaData META_DATA = new com.afm.vhc.intrnl.SearchOrderMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("SearchOrder", com.afm.vhc.SearchOrder.class, "VHC.SearchOrder", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __VBELN ;  
    
    private java.lang.String __DEBITOR_NAME ;  
    
    private java.lang.String __VHVIN ;  
    
    private java.lang.String __LICPL ;  
    
    private java.lang.String __CSTRYEAR ;  
    
    private java.lang.String __SPART_TXT ;  
    
    private java.lang.String __VMODEL_TXT ;  
    
    private java.sql.Date __VISIT_START_DATE ;  
    
    private java.sql.Time __VISIT_START_TIME ;  
    
    private java.lang.String __PNAME ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 88:
            return getSurrogateKey();
        case 1246:
            return getCvpOperationLength();
        case 1247:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 88:
            setSurrogateKey((long)v);
            break;
        case 1246:
            setCvpOperationLength((long)v);
            break;
        case 1247:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 659:
            return getCvpOperation();
        case 660:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 78:
            return getVBELN();
        case 79:
            return getDEBITOR_NAME();
        case 80:
            return getVHVIN();
        case 81:
            return getLICPL();
        case 82:
            return getCSTRYEAR();
        case 83:
            return getSPART_TXT();
        case 84:
            return getVMODEL_TXT();
        case 87:
            return getPNAME();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 78:
            setVBELN((java.lang.String)v);
            break;
        case 79:
            setDEBITOR_NAME((java.lang.String)v);
            break;
        case 80:
            setVHVIN((java.lang.String)v);
            break;
        case 81:
            setLICPL((java.lang.String)v);
            break;
        case 82:
            setCSTRYEAR((java.lang.String)v);
            break;
        case 83:
            setSPART_TXT((java.lang.String)v);
            break;
        case 84:
            setVMODEL_TXT((java.lang.String)v);
            break;
        case 87:
            setPNAME((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public java.sql.Time getAttributeNullableTime(int id)
    {
        switch(id)
        {
        case 86:
            return getVISIT_START_TIME();
        default:
            return super.getAttributeNullableTime(id);
        }
    }
    
    public void setAttributeNullableTime(int id, java.sql.Time v)
    {
        switch(id)
        {
        case 86:
            setVISIT_START_TIME((java.sql.Time)v);
            break;
        default:
            super.setAttributeNullableTime(id, v);
            break;
        }
    }
    public java.sql.Date getAttributeNullableDate(int id)
    {
        switch(id)
        {
        case 85:
            return getVISIT_START_DATE();
        default:
            return super.getAttributeNullableDate(id);
        }
    }
    
    public void setAttributeNullableDate(int id, java.sql.Date v)
    {
        switch(id)
        {
        case 85:
            setVISIT_START_DATE((java.sql.Date)v);
            break;
        default:
            super.setAttributeNullableDate(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.SearchOrder  
     */
    public SearchOrder()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of VBELN  
     */
    public java.lang.String getVBELN()
    {
        
        return __VBELN;
    }
    
    /**
     * Set the value of VBELN  
     */
    public void setVBELN(java.lang.String value)
    {
        if ((__VBELN == null) != (value == null) || (value != null && ! value.equals(__VBELN)))
        {
            _isDirty = true;
        }
        __VBELN = value;
    }       
    /**
     * get the value of DEBITOR_NAME  
     */
    public java.lang.String getDEBITOR_NAME()
    {
        
        return __DEBITOR_NAME;
    }
    
    /**
     * Set the value of DEBITOR_NAME  
     */
    public void setDEBITOR_NAME(java.lang.String value)
    {
        if ((__DEBITOR_NAME == null) != (value == null) || (value != null && ! value.equals(__DEBITOR_NAME)))
        {
            _isDirty = true;
        }
        __DEBITOR_NAME = value;
    }       
    /**
     * get the value of VHVIN  
     */
    public java.lang.String getVHVIN()
    {
        
        return __VHVIN;
    }
    
    /**
     * Set the value of VHVIN  
     */
    public void setVHVIN(java.lang.String value)
    {
        if ((__VHVIN == null) != (value == null) || (value != null && ! value.equals(__VHVIN)))
        {
            _isDirty = true;
        }
        __VHVIN = value;
    }       
    /**
     * get the value of LICPL  
     */
    public java.lang.String getLICPL()
    {
        
        return __LICPL;
    }
    
    /**
     * Set the value of LICPL  
     */
    public void setLICPL(java.lang.String value)
    {
        if ((__LICPL == null) != (value == null) || (value != null && ! value.equals(__LICPL)))
        {
            _isDirty = true;
        }
        __LICPL = value;
    }       
    /**
     * get the value of CSTRYEAR  
     */
    public java.lang.String getCSTRYEAR()
    {
        
        return __CSTRYEAR;
    }
    
    /**
     * Set the value of CSTRYEAR  
     */
    public void setCSTRYEAR(java.lang.String value)
    {
        if ((__CSTRYEAR == null) != (value == null) || (value != null && ! value.equals(__CSTRYEAR)))
        {
            _isDirty = true;
        }
        __CSTRYEAR = value;
    }       
    /**
     * get the value of SPART_TXT  
     */
    public java.lang.String getSPART_TXT()
    {
        
        return __SPART_TXT;
    }
    
    /**
     * Set the value of SPART_TXT  
     */
    public void setSPART_TXT(java.lang.String value)
    {
        if ((__SPART_TXT == null) != (value == null) || (value != null && ! value.equals(__SPART_TXT)))
        {
            _isDirty = true;
        }
        __SPART_TXT = value;
    }       
    /**
     * get the value of VMODEL_TXT  
     */
    public java.lang.String getVMODEL_TXT()
    {
        
        return __VMODEL_TXT;
    }
    
    /**
     * Set the value of VMODEL_TXT  
     */
    public void setVMODEL_TXT(java.lang.String value)
    {
        if ((__VMODEL_TXT == null) != (value == null) || (value != null && ! value.equals(__VMODEL_TXT)))
        {
            _isDirty = true;
        }
        __VMODEL_TXT = value;
    }       
    /**
     * get the value of VISIT_START_DATE  
     */
    public java.sql.Date getVISIT_START_DATE()
    {
        
        return __VISIT_START_DATE;
    }
    
    /**
     * Set the value of VISIT_START_DATE  
     */
    public void setVISIT_START_DATE(java.sql.Date value)
    {
        if ((__VISIT_START_DATE == null) != (value == null) || (value != null && ! value.equals(__VISIT_START_DATE)))
        {
            _isDirty = true;
        }
        __VISIT_START_DATE = value;
    }       
    /**
     * get the value of VISIT_START_TIME  
     */
    public java.sql.Time getVISIT_START_TIME()
    {
        
        return __VISIT_START_TIME;
    }
    
    /**
     * Set the value of VISIT_START_TIME  
     */
    public void setVISIT_START_TIME(java.sql.Time value)
    {
        if ((__VISIT_START_TIME == null) != (value == null) || (value != null && ! value.equals(__VISIT_START_TIME)))
        {
            _isDirty = true;
        }
        __VISIT_START_TIME = value;
    }       
    /**
     * get the value of PNAME  
     */
    public java.lang.String getPNAME()
    {
        
        return __PNAME;
    }
    
    /**
     * Set the value of PNAME  
     */
    public void setPNAME(java.lang.String value)
    {
        if ((__PNAME == null) != (value == null) || (value != null && ! value.equals(__PNAME)))
        {
            _isDirty = true;
        }
        __PNAME = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.SearchOrder find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "SearchOrder.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.SearchOrder)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.SearchOrder load(long id)
    {
        return (com.afm.vhc.SearchOrder)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of SearchOrder
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.SearchOrder> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.SearchOrder>)(Object)DELEGATE.findWithQuery(query, com.afm.vhc.SearchOrder.class);
    }
    
    /**
     * Find a List of Com.afm.vhc.SearchOrder
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.SearchOrder> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "SearchOrder.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"l\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"vhc_1_0_searchorder\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"l\" from \"vhc_1_0_"
                                                + "searchorder_os\" x_os where x_os.\"l\" = x.\"l\"))))"; 
            return (com.sybase.collections.GenericList<com.afm.vhc.SearchOrder>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, com.afm.vhc.SearchOrder.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.SearchOrder  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.SearchOrder> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a mobile business object Com.afm.vhc.SearchOrder
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.SearchOrder findByPrimaryKey(java.lang.String VBELN)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "SearchOrder.findByPrimaryKey";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = "SELECT x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"l\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"vhc_1_0_searchorder\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"l\" from \"vh"
                                        + "c_1_0_searchorder_os\" x_os where x_os.\"l\" = x.\"l\")))) and ( x.\"a\" = ?)";
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    VBELN,
                };
                Object res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, com.afm.vhc.SearchOrder.class);
                return (com.afm.vhc.SearchOrder)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.SearchOrder> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.SearchOrder>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.SearchOrder> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.SearchOrder>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("SearchOrder", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public com.afm.vhc.SearchOrder getDownloadState()
    {
        return (com.afm.vhc.SearchOrder)i_getDownloadState();
    }
    
    public com.afm.vhc.SearchOrder getOriginalState()
    {
        return (com.afm.vhc.SearchOrder)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}