/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class ServerPersonalization extends com.sybase.persistence.AbstractReadOnlyEntity implements com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.ServerPersonalizationMetaData META_DATA = new com.afm.vhc.intrnl.ServerPersonalizationMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("ServerPersonalization", com.afm.vhc.ServerPersonalization.class, "VHC.ServerPersonalization", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __value ;  
    
    private boolean __user_defined  = com.sybase.afx.json.JsonValue.getBoolean("true");  
    
    private java.lang.String __package_script_version ;  
    
    private java.lang.String __key_name ;  
    
    private java.lang.String __user_name ;  
    
    private java.lang.String __package_name ;  
    
    private java.lang.String __domain_name ;  
    
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 617:
            return getValue();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 617:
            setValue((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 616:
            return getPackage_script_version();
        case 612:
            return getKey_name();
        case 613:
            return getUser_name();
        case 614:
            return getPackage_name();
        case 615:
            return getDomain_name();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 616:
            setPackage_script_version((java.lang.String)v);
            break;
        case 612:
            setKey_name((java.lang.String)v);
            break;
        case 613:
            setUser_name((java.lang.String)v);
            break;
        case 614:
            setPackage_name((java.lang.String)v);
            break;
        case 615:
            setDomain_name((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 618:
            return getUser_defined();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 618:
            setUser_defined((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.ServerPersonalization  
     */
    public ServerPersonalization()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of value  
     */
    public java.lang.String getValue()
    {
        
        return __value;
    }
    
    /**
     * Set the value of value  
     */
    public void setValue(java.lang.String value)
    {
        if ((__value == null) != (value == null) || (value != null && ! value.equals(__value)))
        {
            _isDirty = true;
        }
        __value = value;
    }       
    /**
     * get the value of user_defined  
     */
    public boolean getUser_defined()
    {
        
        return __user_defined;
    }
    
    /**
     * Set the value of user_defined  
     */
    public void setUser_defined(boolean value)
    {
        if(__user_defined != value)
        {
            _isDirty = true;
        }
        __user_defined = value;
    }       
    /**
     * get the value of package_script_version  
     */
    public java.lang.String getPackage_script_version()
    {
        
        return __package_script_version;
    }
    
    /**
     * Set the value of package_script_version  
     */
    public void setPackage_script_version(java.lang.String value)
    {
        if ((__package_script_version == null) != (value == null) || (value != null && ! value.equals(__package_script_version)))
        {
            _isDirty = true;
        }
        __package_script_version = value;
    }       
    /**
     * get the value of key_name  
     */
    public java.lang.String getKey_name()
    {
        
        return __key_name;
    }
    
    /**
     * Set the value of key_name  
     */
    public void setKey_name(java.lang.String value)
    {
        if ((__key_name == null) != (value == null) || (value != null && ! value.equals(__key_name)))
        {
            _isDirty = true;
        }
        __key_name = value;
    }       
    /**
     * get the value of user_name  
     */
    public java.lang.String getUser_name()
    {
        
        return __user_name;
    }
    
    /**
     * Set the value of user_name  
     */
    public void setUser_name(java.lang.String value)
    {
        if ((__user_name == null) != (value == null) || (value != null && ! value.equals(__user_name)))
        {
            _isDirty = true;
        }
        __user_name = value;
    }       
    /**
     * get the value of package_name  
     */
    public java.lang.String getPackage_name()
    {
        
        return __package_name;
    }
    
    /**
     * Set the value of package_name  
     */
    public void setPackage_name(java.lang.String value)
    {
        if ((__package_name == null) != (value == null) || (value != null && ! value.equals(__package_name)))
        {
            _isDirty = true;
        }
        __package_name = value;
    }       
    /**
     * get the value of domain_name  
     */
    public java.lang.String getDomain_name()
    {
        
        return __domain_name;
    }
    
    /**
     * Set the value of domain_name  
     */
    public void setDomain_name(java.lang.String value)
    {
        if ((__domain_name == null) != (value == null) || (value != null && ! value.equals(__domain_name)))
        {
            _isDirty = true;
        }
        __domain_name = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.ServerPersonalization find(com.afm.vhc.KeyPackageName id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "ServerPersonalization.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id.getKey_name(),id.getUser_name(),id.getPackage_name(),id.getDomain_name()};
            return (com.afm.vhc.ServerPersonalization)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.ServerPersonalization load(com.afm.vhc.KeyPackageName id)
    {
        return (com.afm.vhc.ServerPersonalization)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public com.afm.vhc.KeyPackageName _pk()
    {
        return (com.afm.vhc.KeyPackageName)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.ServerPersonalization> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.ServerPersonalization>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.ServerPersonalization> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.ServerPersonalization>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("ServerPersonalization", keyToString());
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}