/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class UserInfo extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.UserInfoMetaData META_DATA = new com.afm.vhc.intrnl.UserInfoMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("UserInfo", com.afm.vhc.UserInfo.class, "VHC.UserInfo", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __PEX_WERKS ;  
    
    private java.lang.String __PEX_NAME ;  
    
    private java.lang.String __PEX_SPART ;  
    
    private java.lang.String __PEX_VKORG ;  
    
    private java.lang.String __PEX_BUKRS ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 333:
            return getSurrogateKey();
        case 1382:
            return getCvpOperationLength();
        case 1383:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 333:
            setSurrogateKey((long)v);
            break;
        case 1382:
            setCvpOperationLength((long)v);
            break;
        case 1383:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 885:
            return getCvpOperation();
        case 886:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 328:
            return getPEX_WERKS();
        case 329:
            return getPEX_NAME();
        case 330:
            return getPEX_SPART();
        case 331:
            return getPEX_VKORG();
        case 332:
            return getPEX_BUKRS();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 328:
            setPEX_WERKS((java.lang.String)v);
            break;
        case 329:
            setPEX_NAME((java.lang.String)v);
            break;
        case 330:
            setPEX_SPART((java.lang.String)v);
            break;
        case 331:
            setPEX_VKORG((java.lang.String)v);
            break;
        case 332:
            setPEX_BUKRS((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.UserInfo  
     */
    public UserInfo()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of PEX_WERKS  
     */
    public java.lang.String getPEX_WERKS()
    {
        
        return __PEX_WERKS;
    }
    
    /**
     * Set the value of PEX_WERKS  
     */
    public void setPEX_WERKS(java.lang.String value)
    {
        if ((__PEX_WERKS == null) != (value == null) || (value != null && ! value.equals(__PEX_WERKS)))
        {
            _isDirty = true;
        }
        __PEX_WERKS = value;
    }       
    /**
     * get the value of PEX_NAME  
     */
    public java.lang.String getPEX_NAME()
    {
        
        return __PEX_NAME;
    }
    
    /**
     * Set the value of PEX_NAME  
     */
    public void setPEX_NAME(java.lang.String value)
    {
        if ((__PEX_NAME == null) != (value == null) || (value != null && ! value.equals(__PEX_NAME)))
        {
            _isDirty = true;
        }
        __PEX_NAME = value;
    }       
    /**
     * get the value of PEX_SPART  
     */
    public java.lang.String getPEX_SPART()
    {
        
        return __PEX_SPART;
    }
    
    /**
     * Set the value of PEX_SPART  
     */
    public void setPEX_SPART(java.lang.String value)
    {
        if ((__PEX_SPART == null) != (value == null) || (value != null && ! value.equals(__PEX_SPART)))
        {
            _isDirty = true;
        }
        __PEX_SPART = value;
    }       
    /**
     * get the value of PEX_VKORG  
     */
    public java.lang.String getPEX_VKORG()
    {
        
        return __PEX_VKORG;
    }
    
    /**
     * Set the value of PEX_VKORG  
     */
    public void setPEX_VKORG(java.lang.String value)
    {
        if ((__PEX_VKORG == null) != (value == null) || (value != null && ! value.equals(__PEX_VKORG)))
        {
            _isDirty = true;
        }
        __PEX_VKORG = value;
    }       
    /**
     * get the value of PEX_BUKRS  
     */
    public java.lang.String getPEX_BUKRS()
    {
        
        return __PEX_BUKRS;
    }
    
    /**
     * Set the value of PEX_BUKRS  
     */
    public void setPEX_BUKRS(java.lang.String value)
    {
        if ((__PEX_BUKRS == null) != (value == null) || (value != null && ! value.equals(__PEX_BUKRS)))
        {
            _isDirty = true;
        }
        __PEX_BUKRS = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.UserInfo find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "UserInfo.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.UserInfo)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.UserInfo load(long id)
    {
        return (com.afm.vhc.UserInfo)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of UserInfo
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.UserInfo> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.UserInfo>)(Object)DELEGATE.findWithQuery(query, com.afm.vhc.UserInfo.class);
    }
    
    /**
     * Find a List of Com.afm.vhc.UserInfo
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.UserInfo> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "UserInfo.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"f\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"vhc_1_0_userinfo\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"f\" from \"vhc_1_0_userinfo_os\" x_os where x_os.\"f\" "
                                                + "= x.\"f\"))))"; 
            return (com.sybase.collections.GenericList<com.afm.vhc.UserInfo>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, com.afm.vhc.UserInfo.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.UserInfo  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.UserInfo> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.UserInfo> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.UserInfo>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.UserInfo> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.UserInfo>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("UserInfo", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public com.afm.vhc.UserInfo getDownloadState()
    {
        return (com.afm.vhc.UserInfo)i_getDownloadState();
    }
    
    public com.afm.vhc.UserInfo getOriginalState()
    {
        return (com.afm.vhc.UserInfo)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}