/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class VHCQuestionnaire extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.VHCQuestionnaireMetaData META_DATA = new com.afm.vhc.intrnl.VHCQuestionnaireMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("VHCQuestionnaire", com.afm.vhc.VHCQuestionnaire.class, "VHC.VHCQuestionnaire", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __SECTION_ID ;  
    
    private java.lang.String __SECTION_DESC ;  
    
    private java.lang.String __QUES_ID ;  
    
    private java.lang.String __QUES_DESC ;  
    
    private java.lang.String __QUES_TYPE ;  
    
    private java.lang.String __MANDATORY ;  
    
    private java.lang.String __DEFAUL ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 123:
            return getSurrogateKey();
        case 1269:
            return getCvpOperationLength();
        case 1270:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 123:
            setSurrogateKey((long)v);
            break;
        case 1269:
            setCvpOperationLength((long)v);
            break;
        case 1270:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 699:
            return getCvpOperation();
        case 700:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 116:
            return getSECTION_ID();
        case 117:
            return getSECTION_DESC();
        case 118:
            return getQUES_ID();
        case 119:
            return getQUES_DESC();
        case 120:
            return getQUES_TYPE();
        case 121:
            return getMANDATORY();
        case 122:
            return getDEFAUL();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 116:
            setSECTION_ID((java.lang.String)v);
            break;
        case 117:
            setSECTION_DESC((java.lang.String)v);
            break;
        case 118:
            setQUES_ID((java.lang.String)v);
            break;
        case 119:
            setQUES_DESC((java.lang.String)v);
            break;
        case 120:
            setQUES_TYPE((java.lang.String)v);
            break;
        case 121:
            setMANDATORY((java.lang.String)v);
            break;
        case 122:
            setDEFAUL((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.VHCQuestionnaire  
     */
    public VHCQuestionnaire()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of SECTION_ID  
     */
    public java.lang.String getSECTION_ID()
    {
        
        return __SECTION_ID;
    }
    
    /**
     * Set the value of SECTION_ID  
     */
    public void setSECTION_ID(java.lang.String value)
    {
        if ((__SECTION_ID == null) != (value == null) || (value != null && ! value.equals(__SECTION_ID)))
        {
            _isDirty = true;
        }
        __SECTION_ID = value;
    }       
    /**
     * get the value of SECTION_DESC  
     */
    public java.lang.String getSECTION_DESC()
    {
        
        return __SECTION_DESC;
    }
    
    /**
     * Set the value of SECTION_DESC  
     */
    public void setSECTION_DESC(java.lang.String value)
    {
        if ((__SECTION_DESC == null) != (value == null) || (value != null && ! value.equals(__SECTION_DESC)))
        {
            _isDirty = true;
        }
        __SECTION_DESC = value;
    }       
    /**
     * get the value of QUES_ID  
     */
    public java.lang.String getQUES_ID()
    {
        
        return __QUES_ID;
    }
    
    /**
     * Set the value of QUES_ID  
     */
    public void setQUES_ID(java.lang.String value)
    {
        if ((__QUES_ID == null) != (value == null) || (value != null && ! value.equals(__QUES_ID)))
        {
            _isDirty = true;
        }
        __QUES_ID = value;
    }       
    /**
     * get the value of QUES_DESC  
     */
    public java.lang.String getQUES_DESC()
    {
        
        return __QUES_DESC;
    }
    
    /**
     * Set the value of QUES_DESC  
     */
    public void setQUES_DESC(java.lang.String value)
    {
        if ((__QUES_DESC == null) != (value == null) || (value != null && ! value.equals(__QUES_DESC)))
        {
            _isDirty = true;
        }
        __QUES_DESC = value;
    }       
    /**
     * get the value of QUES_TYPE  
     */
    public java.lang.String getQUES_TYPE()
    {
        
        return __QUES_TYPE;
    }
    
    /**
     * Set the value of QUES_TYPE  
     */
    public void setQUES_TYPE(java.lang.String value)
    {
        if ((__QUES_TYPE == null) != (value == null) || (value != null && ! value.equals(__QUES_TYPE)))
        {
            _isDirty = true;
        }
        __QUES_TYPE = value;
    }       
    /**
     * get the value of MANDATORY  
     */
    public java.lang.String getMANDATORY()
    {
        
        return __MANDATORY;
    }
    
    /**
     * Set the value of MANDATORY  
     */
    public void setMANDATORY(java.lang.String value)
    {
        if ((__MANDATORY == null) != (value == null) || (value != null && ! value.equals(__MANDATORY)))
        {
            _isDirty = true;
        }
        __MANDATORY = value;
    }       
    /**
     * get the value of DEFAUL  
     */
    public java.lang.String getDEFAUL()
    {
        
        return __DEFAUL;
    }
    
    /**
     * Set the value of DEFAUL  
     */
    public void setDEFAUL(java.lang.String value)
    {
        if ((__DEFAUL == null) != (value == null) || (value != null && ! value.equals(__DEFAUL)))
        {
            _isDirty = true;
        }
        __DEFAUL = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.VHCQuestionnaire find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "VHCQuestionnaire.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.VHCQuestionnaire)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.VHCQuestionnaire load(long id)
    {
        return (com.afm.vhc.VHCQuestionnaire)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of VHCQuestionnaire
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire>)(Object)DELEGATE.findWithQuery(query, com.afm.vhc.VHCQuestionnaire.class);
    }
    
    /**
     * Find a List of Com.afm.vhc.VHCQuestionnaire
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "VHCQuestionnaire.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"h\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"vhc_1_0_vhcquestionnaire\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"h\" from \"vhc_1_0_vhcquestionna"
                                                + "ire_os\" x_os where x_os.\"h\" = x.\"h\"))))"; 
            return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, com.afm.vhc.VHCQuestionnaire.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.VHCQuestionnaire  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaire>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("VHCQuestionnaire", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
        com.afm.vhc.VHCQuestionnaireUploadFilesAsXStringOperation.DELEGATE.submitPendingOperations();
        com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation.DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
        com.afm.vhc.VHCQuestionnaireUploadFilesAsXStringOperation.DELEGATE.cancelPendingOperations();
        com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation.DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public com.afm.vhc.VHCQuestionnaire getDownloadState()
    {
        return (com.afm.vhc.VHCQuestionnaire)i_getDownloadState();
    }
    
    public com.afm.vhc.VHCQuestionnaire getOriginalState()
    {
        return (com.afm.vhc.VHCQuestionnaire)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}