/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class VHCQuestionnaireUploadFilesOperation extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.VHCQuestionnaireUploadFilesOperationMetaData META_DATA = new com.afm.vhc.intrnl.VHCQuestionnaireUploadFilesOperationMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("VHCQuestionnaireUploadFilesOperation", com.afm.vhc.VHCQuestionnaireUploadFilesOperation.class, "VHC.VHCQuestionnaireUploadFilesOperation", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __PIM_FILENAME  = com.sybase.afx.json.JsonValue.getString("");  
    
    private java.lang.String __PIM_VBELN  = com.sybase.afx.json.JsonValue.getString("");  
    
    private com.sybase.collections.GenericList<com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT> __PIM_CONTENT ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private boolean __PIM_FILENAMEValid ;  
    
    private boolean __PIM_VBELNValid ;  
    
    private boolean __PIM_CONTENTValid ;  
    
    private long __id ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 195:
            return getId();
        case 1549:
            return getCvpOperationLength();
        case 1550:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 195:
            setId((long)v);
            break;
        case 1549:
            setCvpOperationLength((long)v);
            break;
        case 1550:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 1127:
            return getCvpOperation();
        case 1128:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 189:
            return getPIM_FILENAME();
        case 191:
            return getPIM_VBELN();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 189:
            setPIM_FILENAME((java.lang.String)v);
            break;
        case 191:
            setPIM_VBELN((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 1137:
            return getPIM_FILENAMEValid();
        case 1138:
            return getPIM_VBELNValid();
        case 1139:
            return getPIM_CONTENTValid();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 1137:
            setPIM_FILENAMEValid((boolean)v);
            break;
        case 1138:
            setPIM_VBELNValid((boolean)v);
            break;
        case 1139:
            setPIM_CONTENTValid((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    public java.lang.Object getAttributeObject(int id, boolean loadFromDBIfInvalid)
    {
        switch(id)
        {
        case 193:
            if(loadFromDBIfInvalid)
            {
                return getPIM_CONTENT();
            }
            else
            {
                return __PIM_CONTENT;
            }
        default:
            return super.getAttributeObject(id);
        }
    }
    
    public void setAttributeObject(int id, java.lang.Object v)
    {
        switch(id)
        {
        case 193:
            setPIM_CONTENT((com.sybase.collections.GenericList<com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT>)v);
            break;
        default:
            super.setAttributeObject(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        case 193:
            return com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT.DELEGATE.toJsonArray((getPIM_CONTENT()));
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        case 193:
            setPIM_CONTENT((com.sybase.collections.GenericList<com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT>)com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT.DELEGATE.fromJsonArray((com.sybase.afx.json.JsonArray)value));
            break;
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.VHCQuestionnaireUploadFilesOperation  
     */
    public VHCQuestionnaireUploadFilesOperation()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of PIM_FILENAME  
     */
    public java.lang.String getPIM_FILENAME()
    {
        
        if(__PIM_FILENAMEValid || _isNew)
        {
            return __PIM_FILENAME;
        }
        
        try
        {
            com.sybase.persistence.ConnectionWrapper _conn = _getConn();;
            try
            {
                String sql = "select x.\"a\" from vhc_1_0_vhcquestionnaireuploadfilesoperation x where (x.\"pending\" = 1 or not exists (select x_os.\"d\" from \"vhc_1_0_vhcquestionnaireuploadfilesoperation_os\" x_os where x_os.\"d\" = x.\"d\")) and x.\"d\"=?";
                if(this._isOriginalState)
                {
                	sql = "select x.\"a\" from vhc_1_0_vhcquestionnaireuploadfilesoperation_os x where x.\"d\"=?";
                }
                com.sybase.persistence.ManagedQuery _m_ps = com.sybase.persistence.ManagedQuery.prepare(_conn, sql);
                com.sybase.persistence.StatementWrapper ps = _m_ps.getStatement();
                com.sybase.afx.ulj.StatementUtil.setLong(_conn, ps, "id", 1, __id);
                com.sybase.persistence.ResultSetWrapper rs = ps.executeQuery();
                if (com.sybase.afx.ulj.ResultUtil.next(rs))
                {
                    boolean saveDirty = _isDirty;
                    this.__PIM_FILENAME = com.sybase.afx.ulj.ResultUtil.getString(rs,"PIM_FILENAME",1);
                    _isDirty = saveDirty;
                }
                _m_ps.close();
            }
            catch(com.sybase.persistence.PersistenceException ex)
            {
                throw ex;
            }
        }
        finally
        {
            com.afm.vhc.VHCDB.getDelegate().releaseDBConnection();
        }
        __PIM_FILENAMEValid = true;
        return __PIM_FILENAME;
    }
    
    /**
     * Set the value of PIM_FILENAME  
     */
    public void setPIM_FILENAME(java.lang.String value)
    {
        __PIM_FILENAMEValid = true;
        _isDirty = true;
        __PIM_FILENAME = value;
    }       
    /**
     * get the value of PIM_VBELN  
     */
    public java.lang.String getPIM_VBELN()
    {
        
        if(__PIM_VBELNValid || _isNew)
        {
            return __PIM_VBELN;
        }
        
        try
        {
            com.sybase.persistence.ConnectionWrapper _conn = _getConn();;
            try
            {
                String sql = "select x.\"b\" from vhc_1_0_vhcquestionnaireuploadfilesoperation x where (x.\"pending\" = 1 or not exists (select x_os.\"d\" from \"vhc_1_0_vhcquestionnaireuploadfilesoperation_os\" x_os where x_os.\"d\" = x.\"d\")) and x.\"d\"=?";
                if(this._isOriginalState)
                {
                	sql = "select x.\"b\" from vhc_1_0_vhcquestionnaireuploadfilesoperation_os x where x.\"d\"=?";
                }
                com.sybase.persistence.ManagedQuery _m_ps = com.sybase.persistence.ManagedQuery.prepare(_conn, sql);
                com.sybase.persistence.StatementWrapper ps = _m_ps.getStatement();
                com.sybase.afx.ulj.StatementUtil.setLong(_conn, ps, "id", 1, __id);
                com.sybase.persistence.ResultSetWrapper rs = ps.executeQuery();
                if (com.sybase.afx.ulj.ResultUtil.next(rs))
                {
                    boolean saveDirty = _isDirty;
                    this.__PIM_VBELN = com.sybase.afx.ulj.ResultUtil.getString(rs,"PIM_VBELN",1);
                    _isDirty = saveDirty;
                }
                _m_ps.close();
            }
            catch(com.sybase.persistence.PersistenceException ex)
            {
                throw ex;
            }
        }
        finally
        {
            com.afm.vhc.VHCDB.getDelegate().releaseDBConnection();
        }
        __PIM_VBELNValid = true;
        return __PIM_VBELN;
    }
    
    /**
     * Set the value of PIM_VBELN  
     */
    public void setPIM_VBELN(java.lang.String value)
    {
        __PIM_VBELNValid = true;
        _isDirty = true;
        __PIM_VBELN = value;
    }       
    /**
     * get the value of PIM_CONTENT  
     */
    public com.sybase.collections.GenericList<com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT> getPIM_CONTENT()
    {
        
        if(__PIM_CONTENTValid || _isNew)
        {
            return __PIM_CONTENT;
        }
        
        try
        {
            com.sybase.persistence.ConnectionWrapper _conn = _getConn();;
            try
            {
                String sql = "select x.\"c\" from vhc_1_0_vhcquestionnaireuploadfilesoperation x where (x.\"pending\" = 1 or not exists (select x_os.\"d\" from \"vhc_1_0_vhcquestionnaireuploadfilesoperation_os\" x_os where x_os.\"d\" = x.\"d\")) and x.\"d\"=?";
                if(this._isOriginalState)
                {
                	sql = "select x.\"c\" from vhc_1_0_vhcquestionnaireuploadfilesoperation_os x where x.\"d\"=?";
                }
                com.sybase.persistence.ManagedQuery _m_ps = com.sybase.persistence.ManagedQuery.prepare(_conn, sql);
                com.sybase.persistence.StatementWrapper ps = _m_ps.getStatement();
                com.sybase.afx.ulj.StatementUtil.setLong(_conn, ps, "id", 1, __id);
                com.sybase.persistence.ResultSetWrapper rs = ps.executeQuery();
                if (com.sybase.afx.ulj.ResultUtil.next(rs))
                {
                    boolean saveDirty = _isDirty;
                    String tmp1 = com.sybase.afx.ulj.ResultUtil.getNullableClob(rs,"PIM_CONTENT",1);
                    this.__PIM_CONTENT = (tmp1==null)?null:com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT.DELEGATE.fromJsonArray((com.sybase.afx.json.JsonArray)com.sybase.afx.json.JsonReader.parse(tmp1));
                    _isDirty = saveDirty;
                }
                _m_ps.close();
            }
            catch(com.sybase.persistence.PersistenceException ex)
            {
                throw ex;
            }
        }
        finally
        {
            com.afm.vhc.VHCDB.getDelegate().releaseDBConnection();
        }
        __PIM_CONTENTValid = true;
        return __PIM_CONTENT;
    }
    
    /**
     * Set the value of PIM_CONTENT  
     */
    public void setPIM_CONTENT(com.sybase.collections.GenericList<com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT> value)
    {
        __PIM_CONTENTValid = true;
        _isDirty = true;
        __PIM_CONTENT = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of PIM_FILENAMEValid  
     */
    private boolean getPIM_FILENAMEValid()
    {
        
        return __PIM_FILENAMEValid;
    }
    
    /**
     * Set the value of PIM_FILENAMEValid  
     */
    private void setPIM_FILENAMEValid(boolean value)
    {
        __PIM_FILENAMEValid = value;
    }       
    /**
     * get the value of PIM_VBELNValid  
     */
    private boolean getPIM_VBELNValid()
    {
        
        return __PIM_VBELNValid;
    }
    
    /**
     * Set the value of PIM_VBELNValid  
     */
    private void setPIM_VBELNValid(boolean value)
    {
        __PIM_VBELNValid = value;
    }       
    /**
     * get the value of PIM_CONTENTValid  
     */
    private boolean getPIM_CONTENTValid()
    {
        
        return __PIM_CONTENTValid;
    }
    
    /**
     * Set the value of PIM_CONTENTValid  
     */
    private void setPIM_CONTENTValid(boolean value)
    {
        __PIM_CONTENTValid = value;
    }       
    /**
     * get the value of id  
     */
    public long getId()
    {
        
        return __id;
    }
    
    /**
     * Set the value of id  
     */
    public void setId(long value)
    {
        if(__id != value)
        {
            _isDirty = true;
        }
        __id = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.VHCQuestionnaireUploadFilesOperation find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "VHCQuestionnaireUploadFilesOperation.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.VHCQuestionnaireUploadFilesOperation)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.VHCQuestionnaireUploadFilesOperation load(long id)
    {
        return (com.afm.vhc.VHCQuestionnaireUploadFilesOperation)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * Find a List of Com.afm.vhc.VHCQuestionnaireUploadFilesOperation
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireUploadFilesOperation> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "VHCQuestionnaireUploadFilesOperation.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " o.\"pending\",o.\"_pc\",o.\"_rp\",o.\"_rf\",o.\"d\",o.\"_rc\",o.\"_ds\",o.\"cvpOperation_length\",o.\"cvpOperationLobs_length\" from \"vhc_1_0_vhcquestionnaireuploadfilesoperation\" o where (((o.\"pending\" = 1 or not exists (select o_os.\"d\" from \"vhc_1_0_vhcquestionnaireuploadfilesoperatio"
                                                + "n_os\" o_os where o_os.\"d\" = o.\"d\"))))"; 
            return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireUploadFilesOperation>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, com.afm.vhc.VHCQuestionnaireUploadFilesOperation.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.VHCQuestionnaireUploadFilesOperation  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireUploadFilesOperation> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireUploadFilesOperation> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireUploadFilesOperation>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireUploadFilesOperation> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireUploadFilesOperation>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("VHCQuestionnaireUploadFilesOperation", keyToString());
    }
    
    
    
    
    
    
    
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (getPendingChange() == 'C')
        {
            return "UploadFiles";
        }
        return null;
    }
    
    public com.afm.vhc.VHCQuestionnaireUploadFilesOperation getDownloadState()
    {
        return (com.afm.vhc.VHCQuestionnaireUploadFilesOperation)i_getDownloadState();
    }
    
    public com.afm.vhc.VHCQuestionnaireUploadFilesOperation getOriginalState()
    {
        return (com.afm.vhc.VHCQuestionnaireUploadFilesOperation)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}