/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class VHCQuestionnaireSubmitVHCResultOperation extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static com.afm.vhc.intrnl.VHCQuestionnaireSubmitVHCResultOperationMetaData META_DATA = new com.afm.vhc.intrnl.VHCQuestionnaireSubmitVHCResultOperationMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("VHCQuestionnaireSubmitVHCResultOperation", com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation.class, "VHC.VHCQuestionnaireSubmitVHCResultOperation", META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private com.sybase.collections.GenericList<com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS> __PIM_VHC_RESULTS ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private boolean __PIM_VHC_RESULTSValid ;  
    
    private long __id ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 194:
            return getId();
        case 1500:
            return getCvpOperationLength();
        case 1501:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 194:
            setId((long)v);
            break;
        case 1500:
            setCvpOperationLength((long)v);
            break;
        case 1501:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 1117:
            return getCvpOperation();
        case 1118:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 1127:
            return getPIM_VHC_RESULTSValid();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 1127:
            setPIM_VHC_RESULTSValid((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    public java.lang.Object getAttributeObject(int id, boolean loadFromDBIfInvalid)
    {
        switch(id)
        {
        case 192:
            if(loadFromDBIfInvalid)
            {
                return getPIM_VHC_RESULTS();
            }
            else
            {
                return __PIM_VHC_RESULTS;
            }
        default:
            return super.getAttributeObject(id);
        }
    }
    
    public void setAttributeObject(int id, java.lang.Object v)
    {
        switch(id)
        {
        case 192:
            setPIM_VHC_RESULTS((com.sybase.collections.GenericList<com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS>)v);
            break;
        default:
            super.setAttributeObject(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        case 192:
            return com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS.DELEGATE.toJsonArray((getPIM_VHC_RESULTS()));
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        case 192:
            setPIM_VHC_RESULTS((com.sybase.collections.GenericList<com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS>)com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS.DELEGATE.fromJsonArray((com.sybase.afx.json.JsonArray)value));
            break;
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation  
     */
    public VHCQuestionnaireSubmitVHCResultOperation()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of PIM_VHC_RESULTS  
     */
    public com.sybase.collections.GenericList<com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS> getPIM_VHC_RESULTS()
    {
        
        if(__PIM_VHC_RESULTSValid || _isNew)
        {
            return __PIM_VHC_RESULTS;
        }
        
        try
        {
            com.sybase.persistence.ConnectionWrapper _conn = _getConn();;
            try
            {
                String sql = "select x.\"a\" from vhc_1_0_vhcquestionnairesubmitvhcresultoperation x where (x.\"pending\" = 1 or not exists (select x_os.\"b\" from \"vhc_1_0_vhcquestionnairesubmitvhcresultoperation_os\" x_os where x_os.\"b\" = x.\"b\")) and x.\"b\"=?";
                if(this._isOriginalState)
                {
                	sql = "select x.\"a\" from vhc_1_0_vhcquestionnairesubmitvhcresultoperation_os x where x.\"b\"=?";
                }
                com.sybase.persistence.ManagedQuery _m_ps = com.sybase.persistence.ManagedQuery.prepare(_conn, sql);
                com.sybase.persistence.StatementWrapper ps = _m_ps.getStatement();
                com.sybase.afx.ulj.StatementUtil.setLong(_conn, ps, "id", 1, __id);
                com.sybase.persistence.ResultSetWrapper rs = ps.executeQuery();
                if (com.sybase.afx.ulj.ResultUtil.next(rs))
                {
                    boolean saveDirty = _isDirty;
                    String tmp1 = com.sybase.afx.ulj.ResultUtil.getNullableClob(rs,"PIM_VHC_RESULTS",1);
                    this.__PIM_VHC_RESULTS = (tmp1==null)?null:com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS.DELEGATE.fromJsonArray((com.sybase.afx.json.JsonArray)com.sybase.afx.json.JsonReader.parse(tmp1));
                    _isDirty = saveDirty;
                }
                _m_ps.close();
            }
            catch(com.sybase.persistence.PersistenceException ex)
            {
                throw ex;
            }
        }
        finally
        {
            com.afm.vhc.VHCDB.getDelegate().releaseDBConnection();
        }
        __PIM_VHC_RESULTSValid = true;
        return __PIM_VHC_RESULTS;
    }
    
    /**
     * Set the value of PIM_VHC_RESULTS  
     */
    public void setPIM_VHC_RESULTS(com.sybase.collections.GenericList<com.afm.vhc.Z_MF_SUBMIT_VHC_PIM_VHC_RESULTS> value)
    {
        __PIM_VHC_RESULTSValid = true;
        _isDirty = true;
        __PIM_VHC_RESULTS = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of PIM_VHC_RESULTSValid  
     */
    private boolean getPIM_VHC_RESULTSValid()
    {
        
        return __PIM_VHC_RESULTSValid;
    }
    
    /**
     * Set the value of PIM_VHC_RESULTSValid  
     */
    private void setPIM_VHC_RESULTSValid(boolean value)
    {
        __PIM_VHC_RESULTSValid = value;
    }       
    /**
     * get the value of id  
     */
    public long getId()
    {
        
        return __id;
    }
    
    /**
     * Set the value of id  
     */
    public void setId(long value)
    {
        if(__id != value)
        {
            _isDirty = true;
        }
        __id = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "VHCQuestionnaireSubmitVHCResultOperation.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation load(long id)
    {
        return (com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * Find a List of Com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "VHCQuestionnaireSubmitVHCResultOperation.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " o.\"pending\",o.\"_pc\",o.\"_rp\",o.\"_rf\",o.\"b\",o.\"_rc\",o.\"_ds\",o.\"cvpOperation_length\",o.\"cvpOperationLobs_length\" from \"vhc_1_0_vhcquestionnairesubmitvhcresultoperation\" o where (((o.\"pending\" = 1 or not exists (select o_os.\"b\" from \"vhc_1_0_vhcquestionnairesubmitvhcresult"
                                                + "operation_os\" o_os where o_os.\"b\" = o.\"b\"))))"; 
            return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return com.afm.vhc.LogRecordImpl.findByEntity("VHCQuestionnaireSubmitVHCResultOperation", keyToString());
    }
    
    
    
    
    
    
    
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (getPendingChange() == 'C')
        {
            return "SubmitVHCResult";
        }
        return null;
    }
    
    public com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation getDownloadState()
    {
        return (com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation)i_getDownloadState();
    }
    
    public com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation getOriginalState()
    {
        return (com.afm.vhc.VHCQuestionnaireSubmitVHCResultOperation)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}