/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.2.4.179
 * mbs - false 
 */
package com.afm.vhc;

@SuppressWarnings("all")
public  class Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT extends com.sybase.persistence.AbstractStructure implements com.sybase.reflection.ClassWithMetaData
{
    private static com.afm.vhc.intrnl.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENTMetaData META_DATA = new com.afm.vhc.intrnl.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENTMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT", com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT.class, META_DATA, com.afm.vhc.VHCDB.getDelegate());
    
    /**
     * Creates an instance of com.afm.vhc.Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT  
     */
    public Z_MF_UPLOAD_ATTACHMENT_TO_GOS_PIM_CONTENT()
    {
        this.setClassDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    
    private byte[] __LINE ;  
    
    public byte[] getAttributeBinary(int id)
    {
        switch(id)
        {
        case 55:
            return getLINE();
        default:
            return super.getAttributeBinary(id);
        }
    }
    
    public void setAttributeBinary(int id, byte[] v)
    {
        switch(id)
        {
        case 55:
            setLINE((byte[])v);
            break;
        default:
            super.setAttributeBinary(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    /**
     * get the value of LINE  
     */
    public byte[] getLINE()
    {
        
        return __LINE;
    }
    
    /**
     * Set the value of LINE  
     */
    public void setLINE(byte[] value)
    {
        __LINE = value;
    }
}